husky_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50



# joint_names is used for [`cob_gazebo_ros_control`](https://github.com/nikhilkalige/filter_gazebo_plugins/tree/master/cob_gazebo_ros_control).
# In raw3-6, [`cob_common/cob_description/urdf/ur_arm/ur10_arm.urdf.xacro`](https://github.com/Shentheman/cob_common/blob/10fa859c06a425d28ff215cdf0a167bd3f57153f/cob_description/urdf/ur_arm/ur10_arm.urdf.xacro#L24) extracts the [`${name}/joint_names`](https://github.com/Shentheman/cob_robots/blob/5e76a75d8709e6a50a6cdbc84c13ae04ff731c14/cob_hardware_config/robots/raw3-6/config/arm_controller.yaml#L2).
joint_names: [
  "base_front_left_wheel",
  "base_front_right_wheel",
  "base_rear_left_wheel",
  "base_rear_right_wheel"]



husky_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['base_front_left_wheel', 'base_rear_left_wheel']
  right_wheel: ['base_front_right_wheel', 'base_rear_right_wheel']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  cmd_vel_timeout: 0.25

  # Base frame_id
  base_frame_id: base_base_link

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: false

  # Husky hardware provides wheel velocities
  estimate_velocity_from_position: false

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.875 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 3.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 6.0   # rad/s^2
